disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  - explicit_self
  - unused_import

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - ok
    - URL
    - x
    - y

excluded:
  - Pods
  - devicesimTests
  - devicesimUITests
  - "**/*.generated.swift"

custom_rules:
  comments_space:
    name: "Space After Comment"
    regex: '//\S'
    message: "There should be a space after //"
    severity: warning 